name: GitHub Actions Workflow
on: [push]
jobs:
  pilar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build
        run: docker build -t pilar-app .

      - name: Lint
        run: docker run --rm pilar-app make lint

      - name: Test
        run: docker run --rm pilar-app make test
