name: CI/CD Pilar
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install dependencies
        run: poetry install --no-root --no-interaction

      - name: Run pylint
        run: poetry run pylint . --recursive=true

      - name: Run flake8
        run: poetry run flake8 .

      - name: Run tests
        run: poetry run pytest
