name: GitHub Actions Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Build
        run: |
          echo "Building the Docker image..."
          docker build -t pilar-app .

      - name: Lint
        run: |
          echo "Running lint checks..."
          pip install flake8
          flake8 .

      - name: Test
        run: |
          echo "Running tests..."
          pip install pytest
          pytest

#      - name: Deploy
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          SSH_HOST: ${{ secrets.SSH_HOST }}
#          SSH_USER: ${{ secrets.SSH_USER }}
#        run: |
#          echo "Deploying to Linode..."
#          mkdir -p ~/.ssh
#          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
#          scp -r . $SSH_USER@$SSH_HOST:/path/to/deploy
#          ssh $SSH_USER@$SSH_HOST 'bash -s' < ./deploy.sh
