name: GitHub Actions Workflow
on: [push]
jobs:
  Build-Lint-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          source $HOME/.poetry/env
          poetry --version

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Test
        run: make test
